### ISSUE TITLE
缺少了 hello_world.c 和 hello_world.cpp. SourceFile这个 scene 无法生成

### ISSUE THREAD

**Issue by nigangkaka** [TeddyHuang-00/Manim-Explanations#1]
缺少了 hello_world.c 和 hello_world.cpp. SourceFile这个 scene 无法生成

**Comment by TeddyHuang-00** [comment]
这个自己添加一下就行，这个仓库只会用来放manim相关的代码，避免今后文件结构冗余，这类asset就不放进来了

**Comment by TeddyHuang-00** [comment]
Closing issue
